### ISSUE TITLE
Publish the app on f-droid

### ISSUE THREAD

**Issue by MayeulC** [p-lr/TrekMe#73]
Hey there,

This looks like a nice open source application, I would be delighted to see it on [f-droid](https://f-droid.org).

I am not sure if the app fits the requirements as-is (requirements are: no proprietary software, including libraries, in the APK). If it does, a [merge request](https://gitlab.com/fdroid/fdroiddata/-/merge_requests) would need to be submitted on the f-droid data repository.

This is not necessarily a task you need to perform yourself, but notifying you (and you agreeing) is the first step :)

- [ ] The maintainers (well, @peterLaurence really) agree with publishing the app on f-droid.

Thank you in advance, and thank you for making this open source.

**Comment by peterLaurence** [comment]
This app contains some Google libraries for location retrieval, and a Google Play subscription feature (for IGN France maps).
I just had a quick look at F-Droid Faq, and I read:

> We don’t use proprietary software: Google Play is proprietary software;

So it's looks like I don't fit the requirements, for now. However, I like the idea of open source.

**Comment by MayeulC** [comment]
Well, there are a lot of apps on F-droid that are just the same packages with the google libraries configured out at build time. Unfortunately, I don't know enough to be more specific.

Don't burn yourself out trying to implement this, if someone is motivated enough, they can likely do it, especially if you help them out. You could also reach out to the F-droid community.

Since you seem to not know f-droid, here is a data point: I run an android phone without Google APPS by choice, with F-droid as my only source of applications (except Signal, but that's still open). F-droid can update applications without user interaction with the privileged extension (which Magisk makes easy to install). I do run stuff from other f-droid repositories though, like [fluffychat](https://fluffychat.im/en/fdroid.html) and [bitwarden](https://mobileapp.bitwarden.com/fdroid/). KDE [has](https://community.kde.org/Android/FDroid) an f-droid repository as well. However, those are special cases, I am really thinking of the main repository for TrekMe.

**Comment by olivierfavre** [comment]
Hello,
Very interesting and well done project!
Is this issue still relevant? Has any work been undertaken by you or the F-Droid community to port the project to this store?
Sincerely,

**Comment by IzzySoft** [comment]
Looking at the latest APK, I just see 3 "offenders":

```
Offending libs:
---------------
* BillingClient (/com/android/billingclient): NonFreeComp,NonFreeNet
* Google Mobile Services (/com/google/android/gms): NonFreeComp
* Google Play Core (/com/google/android/play/core): NonFreeNet,NonFreeComp

3 offenders.
```

Billing client could probably be left out (using a build flavor) without loss of any functionality. I'd accept your app to [my repo](https://apt.izzysoft.de/fdroid) with the two left (unless APK size is meanwhile grown a lot), but the latest release you offer here is quite a bit dated (3 years old). Would there be a newer one? Would you then tag newer releases and provide the corresponding APKs attached to them? And are those other two libraries really needed (maybe there are alternatives – but I cannot tell without knowing what you rely on them for)?

**Comment by p-lr** [comment]
As of now, I do not plan to replace Google Mobile Services (/com/google/android/gms) with another solution. If I decide to release a proprietary-free version, I will re-open this.

**Comment by IzzySoft** [comment]
OK – that would still be "acceptable" for my repo. Any opinion on that, @p-lr ? Would you provide recent APKs for it (with the current and future versions)?
