### ISSUE TITLE
[question] How to get a marker Lat/Long position? 

### ISSUE THREAD

**Issue by thegrxp** [p-lr/TrekMe#88]
Hello, that is more a question than an issue.
In the `WmtViewModel` you add a marker with

```
        /* If it's in the bounds, add a marker */
        val projected = projection.doProjection(place.lat, place.lon) ?: return

        val x = normalize(projected[0], X0, X1)
        val y = normalize(projected[1], Y0, Y1)
        updatePlacePosition(mapState, x, y)
```
 
But how would you denormalize and undo the projection of the position? 
More specifically I'm using a world map of OpenStreetMap and I would like to get the Lat/Long at the center of the view rendering the map.       

Again, thank you for this amazing lib!

**Comment by p-lr** [comment]
Normalized coordinates are values between 0 and 1. MapCompose works with normalized coordinates. 
To get the normalized coordinates of the center of the screen, you can use `MapState.visibleBoundingBox` api (it's easy to get the center). Let's say you get (xc, yc).
To denormalize, you first get the projected coordinates:
```
X = X0 + (X1 - X0) * xc
Y = Y0 + (Y1 - Y0) * yc
```
Then, undo the projection:
```
val latLon = projection.undoProjection(X, Y)
```

**Comment by thegrxp** [comment]
Oh I wanted it to be more complicated than it is. Thank you very much
