### ISSUE TITLE
Please provide polygon draw line between markers 

### ISSUE THREAD

**Issue by sriNaniTrst01** [p-lr/TrekMe#93]
Dear Team please provide the polygon line code for the marker in map state

**Comment by p-lr** [comment]
I don't understand what you mean. If you're looking for code, just navigate the project source code and find it yourself.

**Comment by sriNaniTrst01** [comment]
class PolyNewLineLayer
    (
    private val context: Context,
    private val scope: CoroutineScope,
    private val dataStateFlow: Flow<DataState>,
    private val goToRouteFlow: Flow<Route>,
    private val routeInteractor: RouteInteractor,
    ) {
    val isPolyLineShow = MutableStateFlow(false)
    init {
        scope.launch {
            dataStateFlow.collectLatest { (map, mapState) ->
                goToRouteFlow.collectLatest event@{ route ->
                    isPolyLineShow.collectLatest {
                      //  isPolyLineShow.value
                            val routePoints = getRoutePoints(map, route)
                           println(routePoints)
                            ComposeView(context = context).apply {
                                setViewCompositionStrategy(ViewCompositionStrategy.DisposeOnViewTreeLifecycleDestroyed)
                                setContent {
                                    TrekMeTheme {
                                        PathLine(routePoints)
                                    }

                            }
                        }
                    }
                }
            }
        }
    }


    fun toggolePolyLine() {
        isPolyLineShow.value = !isPolyLineShow.value
    }


    private suspend fun findNearestRoute(
        point: Point,
        routesData: kotlin.collections.Map<Route, RouteData>
    ): Route? = withContext(Dispatchers.Default) {
        routesData.minByOrNull {
            val bary = it.value.barycenter.let { b -> Point(b.x, b.y) }
            (point.x - bary.x).pow(2) + (point.y - bary.y).pow(2)
        }?.key
    }

    private suspend fun getRoutePoints(map: Map, route: Route): List<PointIndexed> {
        var i = 0
        return routeInteractor.getExistingMarkerPositions(map, route).map {
            PointIndexed(i++, it.x, it.y)
        }.toList()
    }

    private fun getBarycenter(chunk: List<PointIndexed>): Barycenter {
        var sumX = 0.0
        var sumY = 0.0
        for (pt in chunk) {
            sumX += pt.x
            sumY += pt.y
        }
        return Barycenter(sumX / chunk.size, sumY / chunk.size)
    }

    private suspend fun computeDistance(route: Route, i1: Int, i2: Int): Double {
        return withContext(Dispatchers.Default) {
            val iMin = min(i1, i2)
            val iMax = max(i1, i2)

            val iterator = route.routeMarkers.listIterator(iMin)

            val distanceCalculator = distanceCalculatorFactory(route.elevationTrusted)
            for (i in iMin until iMax) {
                val marker = iterator.next()
                distanceCalculator.addPoint(marker.lat, marker.lon, marker.elevation)
            }

            distanceCalculator.getDistance()
        }
    }

    data class PointIndexed(val index: Int, val x: Double, val y: Double)

    data class DistanceOnRouteControllerRestoreState(val states: MutableList<DistanceOnRouteState>)
    data class DistanceOnRouteState(val route: Route, var i1: Int, var i2: Int)
}

i added this code for draw line but it's not working

**Comment by p-lr** [comment]
Again, you're not explaining clearly what you're trying to achieve. You're reporting issues but you're actually asking assistance for another project. I have no time for this.

**Comment by sriNaniTrst01** [comment]
yes ok sorry actually i need help from your side i am using your project only just how to show polylines in existing your code
